const STORAGE='pjflow_v02';
const state = loadState();
let currentView='dashboard';
let editingId=null;
let currentStep=0;

const steps=['Triagem','Documentação','Faturamento','Consultas','Atualização PJ','Atualização PF','Efetivação'];
const subtitles={
  dashboard:'Acompanhe aberturas, bloqueios e progresso do piloto.',newcase:'Conduza a abertura passo a passo com regras e validações.',cases:'Consulte e retome aberturas salvas no navegador.',rules:'Regras estruturadas usadas pelo piloto Cooperativa 1 + LTDA.',errors:'Base de conhecimento para pendências bloqueantes e não bloqueantes.',about:'Escopo, objetivos e limitações desta versão demonstrativa.'
};

function loadState(){
  try{const s=JSON.parse(localStorage.getItem(STORAGE)); if(s) return s;}catch(e){}
  return {cases:[demoCase()], errors:[...PJFLOW_DATA.defaultErrors]};
}
function saveState(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function demoCase(){return {id:'DEMO-001',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'ATENÇÃO',step:3,data:{flow:'FLX-2026-001',agency:'0001',cnpj:'12345678000190',company:'EMPRESA PILOTO LTDA',tradeName:'PILOTO',openingDate:'2026-08-01',cnae:'0000-0/00',nire:'123456789',partner:'JOÃO DA SILVA',cpf:'12345678900',marital:'CASADO',signature:'ELETRÔNICA',revenue:3200000,ref1:'CLIENTE A',ref2:'CLIENTE B'},answers:{contract:'SIM',idDoc:'SIM',over30:'SIM',revenueDoc:'SIM',twoSignatures:'SIM',iti:'SIM',balance:'N/A',dre:'N/A',marriageCert:'SIM',spouseDoc:'SIM',qsa:'SIM',brflow:'SIM',cpfRegular:'SIM',crc:'SIM',latestContract:'SIM',partnerStart:'SIM',incomeProof:'NÃO',effective:'NÃO',blockingPending:'NÃO'},files:[{name:'cartao_cnpj.pdf',type:'Consulta Receita'},{name:'contrato_social.pdf',type:'Contrato Social'}]}};
function newCaseObj(){return {id:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'EM ANDAMENTO',step:0,data:{flow:'',agency:'',cnpj:'',company:'',tradeName:'',openingDate:'',cnae:'',nire:'',partner:'',cpf:'',birth:'',natural:'',rg:'',rgDate:'',issuer:'',uf:'',marital:'',partnerStartDate:'',signature:'',revenue:'',ref1:'',ref2:'',contact:'',products:'',personalization:'',addressPJ:'',addressPF:'',income:'',notes:''},answers:{},files:[]};}
function getCase(){return state.cases.find(c=>c.id===editingId);}
function setView(v){currentView=v;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.getElementById('pageTitle').textContent=({dashboard:'Visão geral',newcase:editingId?'Abertura '+editingId:'Nova abertura',cases:'Aberturas',rules:'Matriz de regras',errors:'Base de erros',about:'Sobre o piloto'})[v];document.getElementById('pageSubtitle').textContent=subtitles[v];render();}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmtMoney(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function daysOld(date){if(!date)return null; return Math.floor((Date.now()-new Date(date+'T00:00:00').getTime())/86400000);}
function caseEval(c){
  const a=c.answers,d=c.data;let blockers=[],warn=[];
  if(a.contract==='NÃO')blockers.push('Contrato Social ausente');
  if(a.idDoc==='NÃO')blockers.push('Documento de identificação ausente');
  const over30=a.over30==='SIM'||(daysOld(d.openingDate)!==null&&daysOld(d.openingDate)>30);
  if(over30&&a.revenueDoc==='NÃO')blockers.push('Faturamento/declaração obrigatório para empresa > 30 dias');
  if(d.signature==='HÍBRIDA')blockers.push('Assinaturas híbridas não são aceitas');
  if(d.signature==='ELETRÔNICA'&&a.iti!=='SIM')blockers.push('Validação ITI pendente');
  if(Number(d.revenue)>4800000){if(a.balance!=='SIM')blockers.push('Balanço Patrimonial obrigatório');if(a.dre!=='SIM')blockers.push('DRE obrigatória');}
  if(d.marital==='CASADO'){if(a.marriageCert!=='SIM')blockers.push('Certidão de casamento pendente');if(a.spouseDoc!=='SIM')blockers.push('Documento do cônjuge pendente');}
  if(d.marital==='DIVORCIADO'&&a.marriageCert!=='SIM')blockers.push('Certidão com averbação do divórcio pendente');
  if(a.qsa==='NÃO')blockers.push('QSA divergente do fluxo');
  if(a.cpfRegular==='NÃO')blockers.push('CPF não regular');
  if(a.crc==='NÃO')blockers.push('CRC inativo');
  if(a.latestContract==='NÃO')blockers.push('Contrato não é a última alteração');
  if(d.ref1&&d.ref2&&d.ref1.trim().toLowerCase()===d.ref2.trim().toLowerCase())blockers.push('Referências devem ser diferentes');
  if(a.brflow==='NÃO')warn.push('BRFlow não concluído');
  if(a.partnerStart!=='SIM')warn.push('Validar data de entrada do sócio no contrato');
  if(a.incomeProof==='NÃO')warn.push('Aplicar renda presumida (permitido na Coop 1)');
  if(a.effective==='NÃO')warn.push('Conta ainda não efetivada');
  const status=blockers.length?'NÃO PROSSEGUIR':warn.length?'ATENÇÃO':'APTO PARA PROSSEGUIR';
  return {blockers,warn,status};
}
function badge(status){const cls=status==='APTO PARA PROSSEGUIR'||status==='CONCLUÍDO'?'ok':status==='NÃO PROSSEGUIR'?'bad':status==='ATENÇÃO'?'warn':'neutral';return `<span class="badge ${cls}">${esc(status)}</span>`}
function completion(c){const filled=Object.values(c.answers).filter(Boolean).length;return Math.min(100,Math.round((filled/20)*100));}

function render(){const v=document.getElementById('view'); if(currentView==='dashboard')v.innerHTML=dashboard(); if(currentView==='cases')v.innerHTML=casesView(); if(currentView==='rules')v.innerHTML=rulesView(); if(currentView==='errors')v.innerHTML=errorsView(); if(currentView==='about')v.innerHTML=aboutView(); if(currentView==='newcase')v.innerHTML=caseView(); bindDynamic();}
function dashboard(){
  const evals=state.cases.map(c=>caseEval(c));
  const blocked=evals.filter(x=>x.status==='NÃO PROSSEGUIR').length, warn=evals.filter(x=>x.status==='ATENÇÃO').length, ok=evals.filter(x=>x.status==='APTO PARA PROSSEGUIR').length;
  const recent=[...state.cases].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5);
  return `<div class="hero"><h2>Piloto de padronização e mitigação de erros</h2><p>O operador segue uma trilha guiada. As regras são aplicadas durante o preenchimento e a Ficha Inteligente centraliza os dados que serão reutilizados nas etapas seguintes.</p><button class="btn" data-action="new">Iniciar uma abertura</button></div>
  <div class="grid cols-4" style="margin-top:18px"><div class="card metric"><div class="label">Aberturas salvas</div><div class="value">${state.cases.length}</div><div class="hint">armazenadas localmente</div></div><div class="card metric"><div class="label">Bloqueadas</div><div class="value">${blocked}</div><div class="hint">não devem prosseguir</div></div><div class="card metric"><div class="label">Com atenção</div><div class="value">${warn}</div><div class="hint">possuem validações pendentes</div></div><div class="card metric"><div class="label">Aptas</div><div class="value">${ok}</div><div class="hint">sem bloqueios conhecidos</div></div></div>
  <div class="grid cols-2" style="margin-top:18px"><div class="card"><div class="section-title"><div><h2>Aberturas recentes</h2><p>Retome um caso para demonstrar o fluxo.</p></div></div>${recent.length?caseTable(recent):'<div class="empty">Nenhuma abertura.</div>'}</div><div class="card"><div class="section-title"><div><h2>O que este piloto demonstra</h2></div></div><div class="summary-list"><div class="summary-item"><span>Padronização</span><strong>próximo passo guiado</strong></div><div class="summary-item"><span>Mitigação</span><strong>bloqueios antes do erro</strong></div><div class="summary-item"><span>Produtividade</span><strong>ficha única de dados</strong></div><div class="summary-item"><span>Conhecimento</span><strong>base de erros e soluções</strong></div><div class="summary-item"><span>Escalabilidade</span><strong>regras separadas do fluxo</strong></div></div></div></div>`;
}
function caseTable(arr){return `<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Fluxo</th><th>Empresa</th><th>Status</th><th>Progresso</th><th></th></tr></thead><tbody>${arr.map(c=>{const ev=caseEval(c);return `<tr><td>${esc(c.id)}</td><td>${esc(c.data.flow)}</td><td>${esc(c.data.company||'—')}</td><td>${badge(ev.status)}</td><td>${completion(c)}%</td><td><button class="btn secondary" data-open="${esc(c.id)}">Abrir</button></td></tr>`}).join('')}</tbody></table></div>`}
function casesView(){return `<div class="card"><div class="section-title"><div><h2>Aberturas salvas</h2><p>Os dados ficam somente neste navegador nesta versão.</p></div><button class="btn primary" data-action="new">+ Nova abertura</button></div>${state.cases.length?caseTable(state.cases):'<div class="empty">Nenhuma abertura salva.</div>'}</div>`}
function rulesView(){return `<div class="card"><div class="section-title"><div><h2>Matriz de regras</h2><p>Separar regras do fluxo facilita manutenção e futura expansão para outras cooperativas/tipos empresariais.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Categoria</th><th>Condição</th><th>Resultado</th><th>Classificação</th></tr></thead><tbody>${PJFLOW_DATA.rules.map(r=>`<tr><td>${r.id}</td><td>${r.category}</td><td>${r.condition}</td><td>${r.result}</td><td>${badge(r.severity==='Bloqueante'?'NÃO PROSSEGUIR':r.severity==='Atenção'?'ATENÇÃO':'APTO PARA PROSSEGUIR')}</td></tr>`).join('')}</tbody></table></div></div>`}
function errorsView(){return `<div class="card"><div class="section-title"><div><h2>Base de erros e soluções</h2><p>Cadastre ocorrências reais conforme forem sendo mapeadas.</p></div><button class="btn primary" data-add-error>+ Adicionar erro</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Etapa</th><th>Bloqueante?</th><th>Mensagem</th><th>Causa provável</th><th>Solução</th><th></th></tr></thead><tbody>${state.errors.map((e,i)=>`<tr><td>${esc(e.code)}</td><td>${esc(e.stage)}</td><td>${esc(e.blocking)}</td><td>${esc(e.message)}</td><td>${esc(e.cause)}</td><td>${esc(e.solution)}</td><td><button class="btn danger" data-del-error="${i}">Excluir</button></td></tr>`).join('')}</tbody></table></div></div>`}
function aboutView(){return `<div class="grid cols-2"><div class="card"><h2>Objetivo</h2><p>Demonstrar, na prática, como um fluxo guiado pode reduzir dependência de memória, padronizar decisões e evitar que uma abertura avance com validações críticas pendentes.</p><h3>Escopo atual</h3><p>Cooperativa 1 + LTDA. O projeto foi estruturado para receber novos tipos empresariais e cooperativas futuramente.</p><h3>Princípio central</h3><div class="rule-box"><strong>Capturar uma vez → validar → reutilizar</strong>A Ficha Inteligente concentra os dados necessários para as etapas seguintes.</div></div><div class="card"><h2>Limitações desta versão</h2><p class="notice">Este protótipo é local e demonstrativo. Não integra com sistemas bancários, Receita, Junta, ITI, CRC ou BRFlow. Uploads são apenas referências visuais e não há extração real de documentos nesta versão.</p><h3>Próximos passos possíveis</h3><ul><li>Integração com fontes permitidas pela empresa.</li><li>Extração assistida de documentos e consultas.</li><li>Controle de usuários e histórico por operador.</li><li>Métricas de erro, retrabalho e tempo por etapa.</li><li>Base central de regras e pendências.</li></ul></div></div>`}

function caseView(){
  if(!editingId){const c=newCaseObj();c.id='AB-'+Date.now().toString().slice(-6);state.cases.unshift(c);editingId=c.id;currentStep=0;saveState();}
  const c=getCase(); const ev=caseEval(c); c.status=ev.status; c.step=currentStep; c.updatedAt=new Date().toISOString();saveState();
  return `<div class="steps">${steps.map((s,i)=>`<button class="step-pill ${i===currentStep?'active':''} ${i<currentStep?'done':''}" data-step="${i}">${i+1}. ${s}</button>`).join('')}</div>
  <div class="case-layout"><div>${stepCard(c,currentStep,ev)}</div><aside class="sticky-panel"><div class="card"><div class="section-title"><div><h2>Ficha Inteligente</h2><p>Dados capturados para reutilização.</p></div>${badge(ev.status)}</div><div class="progress"><span style="width:${completion(c)}%"></span></div><div class="kpi-row"><span class="mini-kpi">${ev.blockers.length} bloqueios</span><span class="mini-kpi">${ev.warn.length} atenções</span><span class="mini-kpi">${completion(c)}% checklist</span></div><div class="summary-list" style="margin-top:14px">${summary(c)}</div>${ev.blockers.length?`<div class="rule-box bad"><strong>Não prosseguir</strong>${ev.blockers.map(x=>'• '+esc(x)).join('<br>')}</div>`:''}${!ev.blockers.length&&ev.warn.length?`<div class="rule-box warn"><strong>Atenções</strong>${ev.warn.map(x=>'• '+esc(x)).join('<br>')}</div>`:''}</div></aside></div>`;
}
function summary(c){const d=c.data;return [['Fluxo',d.flow],['CNPJ',d.cnpj],['Razão Social',d.company],['Nome Fantasia',d.tradeName],['Data abertura',d.openingDate],['NIRE',d.nire],['Sócio',d.partner],['CPF',d.cpf],['Faturamento',d.revenue?fmtMoney(d.revenue):''],['Agência',d.agency]].map(([a,b])=>`<div class="summary-item"><span>${a}</span><strong>${esc(b||'—')}</strong></div>`).join('')}
function input(name,label,value,type='text',full=false,extra=''){return `<div class="field ${full?'full':''}"><label>${label}</label><input data-field="${name}" type="${type}" value="${esc(value||'')}" ${extra}></div>`}
function select(name,label,value,opts,full=false){return `<div class="field ${full?'full':''}"><label>${label}</label><select data-field="${name}"><option value="">Selecione</option>${opts.map(o=>`<option ${value===o?'selected':''}>${o}</option>`).join('')}</select></div>`}
function ans(name,label,value,opts=['SIM','NÃO','N/A']){return `<div class="check-row"><div><strong>${label}</strong></div><select data-answer="${name}"><option value="">Selecione</option>${opts.map(o=>`<option ${value===o?'selected':''}>${o}</option>`).join('')}</select><div>${answerBadge(name,value)}</div></div>`}
function answerBadge(name,v){if(!v)return '<span class="badge neutral">Pendente</span>';return `<span class="badge ${v==='NÃO'?'warn':'ok'}">${esc(v)}</span>`}
function navButtons(){return `<div class="actions-row"><button class="btn secondary" data-prev ${currentStep===0?'disabled':''}>← Anterior</button><div><button class="btn secondary" data-save>Salvar</button> <button class="btn primary" data-next>${currentStep===steps.length-1?'Concluir demonstração':'Próxima etapa →'}</button></div></div>`}
function fileArea(c,type){const files=c.files.filter(f=>f.type===type);return `<div class="file-drop"><strong>Anexos — ${type}</strong><div class="notice">Nesta versão, o arquivo é apenas referenciado; não há leitura automática.</div><input type="file" data-upload="${type}" multiple><div class="files-list">${files.map((f,i)=>`<div class="file-chip"><span>${esc(f.name)}</span><span>${esc(f.type)}</span></div>`).join('')}</div></div>`}
function stepCard(c,i,ev){const d=c.data,a=c.answers;
 if(i===0)return `<div class="card"><div class="section-title"><div><h2>1. Triagem</h2><p>Identifique o fluxo e capture os dados principais uma única vez.</p></div></div><div class="form-grid">${input('flow','Número do fluxo',d.flow)}${input('agency','Agência',d.agency)}${input('cnpj','CNPJ',d.cnpj)}${input('company','Razão Social',d.company)}${input('partner','Sócio administrador',d.partner)}${input('cpf','CPF do sócio',d.cpf)}${input('contact','Contato da empresa',d.contact)}${input('products','Produtos solicitados',d.products,false)}${input('personalization','Dados de personalização',d.personalization,false)}${input('ref1','Referência 1',d.ref1)}${input('ref2','Referência 2',d.ref2)}</div><div class="rule-box"><strong>Automação futura</strong>Os dados do fluxo podem alimentar automaticamente a Ficha Inteligente, evitando copiar/colar em bloco de notas.</div>${navButtons()}</div>`;
 if(i===1)return `<div class="card"><div class="section-title"><div><h2>2. Validação documental</h2><p>Regras que definem se a abertura pode seguir.</p></div></div><div class="checklist">${ans('contract','Contrato Social registrado na Junta anexado?',a.contract)}${ans('idDoc','Documento de identificação do sócio anexado?',a.idDoc)}</div><div class="form-grid" style="margin-top:14px">${input('openingDate','Data de abertura da empresa',d.openingDate,'date')}${select('marital','Estado civil do sócio',d.marital,['SOLTEIRO','CASADO','DIVORCIADO','UNIÃO ESTÁVEL','VIÚVO','OUTRO'])}</div><div class="checklist" style="margin-top:14px">${ans('over30','Empresa possui mais de 30 dias?',a.over30)}${ans('revenueDoc','Faturamento dos últimos 12 meses ou declaração apresentado?',a.revenueDoc)}${d.marital==='CASADO'?ans('marriageCert','Certidão de casamento anexada?',a.marriageCert):d.marital==='DIVORCIADO'?ans('marriageCert','Certidão com averbação do divórcio anexada?',a.marriageCert):''}${d.marital==='CASADO'?ans('spouseDoc','Documento de identificação do cônjuge anexado?',a.spouseDoc):''}</div>${fileArea(c,'Documentação')}${navButtons()}</div>`;
 if(i===2)return `<div class="card"><div class="section-title"><div><h2>3. Faturamento e assinaturas</h2><p>Aplique regras financeiras e valide assinaturas.</p></div></div><div class="form-grid">${input('revenue','Faturamento total',d.revenue,'number')}${select('signature','Tipo das assinaturas',d.signature,['MANUAL','ELETRÔNICA','HÍBRIDA'])}</div><div class="checklist" style="margin-top:14px">${ans('twoSignatures','Documento possui assinatura do sócio administrador e do contador?',a.twoSignatures)}${d.signature==='ELETRÔNICA'?ans('iti','Assinaturas validadas no ITI?',a.iti):''}${Number(d.revenue)>4800000?ans('balance','Balanço Patrimonial anexado?',a.balance):''}${Number(d.revenue)>4800000?ans('dre','DRE anexada?',a.dre):''}</div>${d.signature==='HÍBRIDA'?'<div class="rule-box bad"><strong>Bloqueio automático</strong>Assinaturas híbridas não são aceitas.</div>':''}${Number(d.revenue)>4800000?'<div class="rule-box warn"><strong>Regra ativa</strong>Faturamento acima de R$ 4,8 milhões exige Balanço Patrimonial e DRE.</div>':''}${fileArea(c,'Faturamento')}${navButtons()}</div>`;
 if(i===3)return `<div class="card"><div class="section-title"><div><h2>4. Consultas externas</h2><p>Execute as consultas e alimente a Ficha Inteligente.</p></div></div><div class="form-grid">${input('tradeName','Nome fantasia',d.tradeName)}${input('cnae','CNAE',d.cnae)}${input('nire','NIRE',d.nire)}${input('addressPJ','Endereço PJ',d.addressPJ)}</div><div class="checklist" style="margin-top:14px">${ans('qsa','QSA da Receita confere com os sócios do fluxo?',a.qsa)}${ans('brflow','Documento passou pelo BRFlow?',a.brflow)}${ans('cpfRegular','CPF está regular na Receita?',a.cpfRegular)}${ans('crc','CRC do contador está ativo?',a.crc)}${ans('latestContract','Contrato enviado é a última alteração da Junta?',a.latestContract)}</div>${fileArea(c,'Consultas')}${navButtons()}</div>`;
 if(i===4)return `<div class="card"><div class="section-title"><div><h2>5. Atualização PJ</h2><p>Use a ficha como fonte única para os campos do sistema.</p></div></div><div class="rule-box ok"><strong>Dados já disponíveis na ficha</strong>Razão Social, Nome Fantasia, CNAE, endereço, NIRE, data de abertura, faturamento, agência, contatos e referências.</div><div class="checklist">${ans('preCadastro','Já existe pré-cadastro para o CNPJ?',a.preCadastro)}${ans('refsDifferent','Referências são diferentes?',a.refsDifferent)}</div><div class="form-grid" style="margin-top:14px">${input('contact','Contato da empresa',d.contact)}${input('ref1','Referência 1',d.ref1)}${input('ref2','Referência 2',d.ref2)}${input('products','Produtos solicitados',d.products)}${input('notes','Observações da atualização PJ',d.notes,'text',true)}</div>${navButtons()}</div>`;
 if(i===5)return `<div class="card"><div class="section-title"><div><h2>6. Atualização PF</h2><p>Complete dados do sócio e valide a data correta de entrada.</p></div></div><div class="form-grid">${input('birth','Data de nascimento',d.birth,'date')}${input('natural','Naturalidade',d.natural)}${input('rg','RG',d.rg)}${input('rgDate','Data de emissão',d.rgDate,'date')}${input('issuer','Órgão emissor',d.issuer)}${input('uf','UF',d.uf)}${input('addressPF','Endereço PF',d.addressPF)}${input('partnerStartDate','Data de início na empresa',d.partnerStartDate,'date')}${input('income','Renda cadastrada',d.income,'number')}</div><div class="checklist" style="margin-top:14px">${ans('partnerStart','Data de entrada do sócio foi validada no contrato?',a.partnerStart)}${ans('incomeProof','Comprovante de renda apresentado?',a.incomeProof)}</div>${a.incomeProof==='NÃO'?'<div class="rule-box ok"><strong>Regra da Cooperativa 1</strong>Sem comprovante de renda, pode ser utilizada renda presumida.</div>':''}${navButtons()}</div>`;
 return `<div class="card"><div class="section-title"><div><h2>7. Produtos e efetivação</h2><p>Finalize a abertura e consulte a base de erros quando necessário.</p></div></div><div class="form-grid">${input('products','Produtos',d.products)}${input('personalization','Personalização dos produtos',d.personalization)}</div><div class="checklist" style="margin-top:14px">${ans('effective','Conta foi efetivada?',a.effective)}${a.effective==='NÃO'?ans('blockingPending','Existe pendência bloqueante?',a.blockingPending):''}</div>${a.effective==='NÃO'?`<div class="rule-box warn"><strong>Se houver erro</strong>Consulte a Base de Erros. Se o erro não estiver mapeado, escale e registre a nova ocorrência para ampliar a base de conhecimento.</div>`:''}<div class="card" style="margin-top:14px;background:#fafbfd"><strong>Resultado atual</strong><div style="margin-top:8px">${badge(ev.status)}</div>${ev.blockers.length?`<p class="notice">Bloqueios: ${ev.blockers.map(esc).join('; ')}</p>`:''}</div>${navButtons()}</div>`;
}

function bindDynamic(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
 document.querySelectorAll('[data-action="new"]').forEach(b=>b.onclick=()=>{editingId=null;currentStep=0;setView('newcase')});
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{editingId=b.dataset.open;currentStep=getCase()?.step||0;setView('newcase')});
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{currentStep=Number(b.dataset.step);render()});
 document.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const c=getCase();c.data[el.dataset.field]=el.value;c.updatedAt=new Date().toISOString();saveState();renderSidebarOnlyMaybe()});
 document.querySelectorAll('[data-answer]').forEach(el=>el.onchange=()=>{const c=getCase();c.answers[el.dataset.answer]=el.value;c.updatedAt=new Date().toISOString();saveState();render()});
 document.querySelectorAll('[data-upload]').forEach(el=>el.onchange=()=>{const c=getCase();[...el.files].forEach(f=>c.files.push({name:f.name,type:el.dataset.upload,size:f.size}));saveState();toast('Anexo referenciado no caso');render()});
 const p=document.querySelector('[data-prev]');if(p)p.onclick=()=>{currentStep=Math.max(0,currentStep-1);render()}; const n=document.querySelector('[data-next]');if(n)n.onclick=()=>{const c=getCase();c.updatedAt=new Date().toISOString();saveState();if(currentStep<steps.length-1){currentStep++;render()}else{toast('Demonstração concluída e salva')}}; const s=document.querySelector('[data-save]');if(s)s.onclick=()=>{saveState();toast('Abertura salva localmente')};
 document.querySelectorAll('[data-del-error]').forEach(b=>b.onclick=()=>{state.errors.splice(Number(b.dataset.delError),1);saveState();render()});
 const add=document.querySelector('[data-add-error]');if(add)add.onclick=()=>{const code=prompt('Código/erro:');if(!code)return;state.errors.push({code,stage:prompt('Etapa:')||'',blocking:prompt('Bloqueante? SIM/NÃO:')||'NÃO',message:prompt('Mensagem apresentada:')||'',cause:prompt('Causa provável:')||'',solution:prompt('Solução validada:')||''});saveState();render()};
}
function renderSidebarOnlyMaybe(){const c=getCase();if(!c)return;const evalNow=caseEval(c);c.status=evalNow.status;saveState();}

document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)});
document.getElementById('newCaseTop').onclick=()=>{editingId=null;currentStep=0;setView('newcase')};
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pjflow-dados.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj.cases||!obj.errors)throw new Error();state.cases=obj.cases;state.errors=obj.errors;saveState();toast('Dados importados');setView('dashboard')}catch(err){toast('Arquivo inválido')}};

render();
